# Generated by Django 4.1.7 on 2023-03-04 07:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('flag', sorl.thumbnail.fields.ImageField(upload_to='flags/')),
                ('city', models.CharField(max_length=128)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=128)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=128)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('reception_day', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=64)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=128)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField()),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
