# Generated by Django 4.1.7 on 2023-03-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_vacancy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contact.vacancy'),
        ),
    ]
