# Generated by Django 4.1.7 on 2023-03-04 07:17

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('instagrampost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.instagrampost')),
                ('description', models.CharField(max_length=100)),
            ],
            bases=('social.instagrampost',),
        ),
    ]
