# Generated by Django 4.1.7 on 2023-03-06 05:50

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='instagram/'),
        ),
    ]
