# Generated by Django 4.1.7 on 2023-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_instagrampost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='instagram'),
        ),
    ]
